stages:
  - build
  - deploy

variables:
  NODE_VERSION: "18"
  DEPLOY_PATH: "/var/www/nextjs-app"

# Build stage
build:
  stage: build
  image: node:${NODE_VERSION}-alpine
  cache:
    paths:
      - node_modules/
      - .next/cache/
  script:
    - npm ci
    - npm run build
    - npm run export # If using static export
  artifacts:
    paths:
      - out/ # For static export
      - .next/ # For server-side rendering
      - node_modules/
      - package*.json
    expire_in: 1 hour
  only:
    - master  # ← Added master branch
    - main
    - develop

# Deploy stage
deploy:
  stage: deploy
  tags:
    - deploy
    - nextjs
  dependencies:
    - build
  script:
    # Create deployment directory
    - sudo mkdir -p ${DEPLOY_PATH}

    # Stop existing application (if using PM2)
    - sudo pm2 stop nextjs-app || true

    # Copy files to deployment directory
    - sudo cp -r .next ${DEPLOY_PATH}/
    - sudo cp -r node_modules ${DEPLOY_PATH}/
    - sudo cp -r public ${DEPLOY_PATH}/ || true
    - sudo cp package*.json ${DEPLOY_PATH}/

    # If using static export, copy out/ directory instead
    # - sudo cp -r out/* ${DEPLOY_PATH}/

    # Set proper permissions
    - sudo chown -R www-data:www-data ${DEPLOY_PATH}

    # Install PM2 if not installed
    - sudo npm install -g pm2 || true

    # Start/restart the application
    - cd ${DEPLOY_PATH}
    - sudo pm2 start npm --name "nextjs-app" -- start || sudo pm2 restart nextjs-app
    - sudo pm2 save
    - sudo pm2 startup || true

  only:
    - master  # ← Added master branch
    - main
  environment:
    name: production
    url: http://10.0.0.201:3000

# Optional: Deploy to staging
deploy_staging:
  stage: deploy
  tags:
    - deploy
  dependencies:
    - build
  script:
    - sudo mkdir -p /var/www/nextjs-app-staging
    - sudo cp -r .next /var/www/nextjs-app-staging/
    - sudo cp -r node_modules /var/www/nextjs-app-staging/
    - sudo cp -r public /var/www/nextjs-app-staging/ || true
    - sudo cp package*.json /var/www/nextjs-app-staging/
    - sudo chown -R www-data:www-data /var/www/nextjs-app-staging
    - cd /var/www/nextjs-app-staging
    - sudo pm2 start npm --name "nextjs-app" -- start || sudo pm2 restart nextjs-app-staging
  only:
    - develop
  environment:
    name: staging
    url: http://10.0.0.201:3001